### ISSUE TITLE
dataset interface ideas

### ISSUE THREAD

**Issue by karissa** [ropensci/rdat#5]
hey @jeroenooms !

Do you have time to chat about some ideas regarding the interface?

Datasets will be required. That is, your current setup will fail when beta is released unless a user supplies  `-d <dataset-name>`
e.g.,
`cat data.json | dat import -d <dataset-name>  -`

In the [python library](github.com/karissa/datpy) I've been working on, I've been toying with the idea of supplying this every time a person runs a command, so 
```python
from datpy import Dat
import pandas as pd

dat = Dat()

## initialize dat
dat.init(tempdir())

df = pd.read_csv('cities.csv')

## uses the unique column 'city_code' to identify and version rows over time
v1 = dat.import_dataframe(df, dataset="cities", key="city_code")

## get the data at a certain version
df = dat.as_dataframe(dataset="cities", checkout=v1)
```

But I'm thinking that it might be a little bit too verbose if people are often working with the same dataset. What if the user could set the dataset at the time of creating the repo?

in R,
```R
repo = Dat('path/to/data', dataset='cities')
repo$import_file('blah.csv')
```

and change the dataset by reinitializing or setting a property.
```R
repo$dataset <- 'population_models'
```

What do you think of these two approaches, how do you imagine people using dat?

On later thoughts, maybe it would make sense to have a Dataset class or something that is initialized separately and analogous to a Dataframe, because its unclear if the Dat has been initialized yet, so setting the dataset there could seem strange

**Comment by karthik** [comment]
It feels a bit unintuitive in the current form:

```r
repo = Dat('path/to/data', dataset='cities')
repo$import_file('blah.csv')
and change the dataset by reinitializing or setting a property.

repo$dataset <- 'population_models'
```

Where does the `population_models` dataset exist? in `path/to/data`?

**Comment by jeroenooms** [comment]
Yes, actually I was using the second approach (specifying a dataset when creating the repo) before but I removed it because the `-d` flag was not working for all commands. But we can easily add it back.

**Comment by karissa** [comment]
@jeroenooms okay that makes sense. -d flag will only work for commands related to datasets, not all commands. there is a reference here that is mostly finalized and 75% implemented. https://github.com/maxogden/dat/blob/beta/beta-cli-api.md

@karthik yeah.. maybe it isn't super intuitive.

One thing I have done for the python library is allow the user to supply arbitrary `**kwargs` keyword arguments for each function that get expanded -- that way, the maintainers of the packages won't have to  redocument all of the available options right now, just using the beta cli as the main reference. https://github.com/karissa/datpy/blob/master/dat.py#L90

We could just use that right now.. is that possible in R?

**Comment by karissa** [comment]
I guess possible is less the right word, EVERYTHING IS POSSIBLE! muhaha

more like, do people do that usually/how does it feel?

**Comment by jeroenooms** [comment]
Let me pull the latest rdat and try.

**Comment by karthik** [comment]
> that way, the maintainers of the packages won't have to redocument all of the available options right now, just using the beta cli as the main reference.

I don't know of a way to do that. Hopefully by the beta things wont change as often which would be super frustrating from the user side.

**Comment by karissa** [comment]
@karthik yeah, part of the reason its taken so long is that we want to make sure we won't have breaking changes the interface after we declare beta
